---
# Task file: include from a play using `ansible.builtin.include_tasks`.
- name: copy dotfiles
  become: true
  block:

    - name: copy .bashrc
      copy:
        src: dotfiles/bashrc
        dest: /home/jack/.bashrc
        owner: jack
        group: jack

    - name: copy .bash_coloring
      copy:
        src: dotfiles/bash_coloring
        dest: /home/jack/.bash_coloring
        owner: jack
        group: jack

    - name: copy .bash_aliases
      copy:
        src: dotfiles/bash_aliases
        dest: /home/jack/.bash_aliases
        owner: jack
        group: jack

    - name: copy .gitconfig
      copy:
        src: dotfiles/gitconfig
        dest: /home/jack/.gitconfig
        owner: jack
        group: jack

    - name: copy .tmux.conf
      copy:
        src: dotfiles/tmux.conf
        dest: /home/jack/.tmux.conf
        owner: jack
        group: jack
