---
# Task file: include from a play using `ansible.builtin.include_tasks`.
- name: copy dotfiles
  become: true
  block:

    - name: copy .bashrc
      copy:
        src: dotfiles/bashrc
        dest: /home/josef/.bashrc
        owner: josef
        group: josef

    - name: copy .bash_coloring
      copy:
        src: dotfiles/bash_coloring
        dest: /home/josef/.bash_coloring
        owner: josef
        group: josef

    - name: copy .bash_aliases
      copy:
        src: dotfiles/bash_aliases
        dest: /home/josef/.bash_aliases
        owner: josef
        group: josef

    - name: copy .gitconfig
      copy:
        src: dotfiles/gitconfig
        dest: /home/josef/.gitconfig
        owner: josef
        group: josef

    - name: copy .tmux.conf
      copy:
        src: dotfiles/tmux.conf
        dest: /home/josef/.tmux.conf
        owner: josef
        group: josef
