---
- name: Install Git on Ubuntu 24.04
  hosts: localhost
  connection: local
  tasks:
    - name: Install apt software
      become: true
      ansible.builtin.apt:
        name:
          - vim
          - git
          - libfuse2t64
          - tmux
          - curl
        state: latest
        update_cache: yes
    
    - name: Install Chrome
      ansible.builtin.include_tasks: install_chrome.yml

    - name: Install Docker
      ansible.builtin.include_tasks: install_docker.yml

    - name: Install Joplin 
      become: false
      ansible.builtin.shell:
        cmd: "wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash"
        creates: ~/.joplin/Joplin.AppImage  # Prevents re-running if already installed
