---
- name: Install Git on Ubuntu 24.04
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install apt packages
      apt:
        name:
          - vim-nox
          - git
          - libfuse2t64
          - tmux
          - curl
          - btop
          - yamllint
        state: latest
        update_cache: true

#    - name: Set wallpaper
#      become_user: jack
#      dconf:
#        key: "/org/gnome/desktop/background/picture-uri"
#        value: "'file:///usr/share/backgrounds/ubuntu-default-greyscale-wallpaper.png'"

    - name: copy dotfiles
      include_tasks: dotfiles/dotfiles.yml

    - name: Install Chrome
      include_tasks: install_chrome.yml

    - name: Install Docker
      include_tasks: install_docker.yml

    - name: Install Joplin
      become: false
      shell:
        cmd: "wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash"
        creates: ~/.joplin/Joplin.AppImage  # Prevents re-running if already installed
