---
- name: Workstation Setup for Ubuntu 26.04
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install apt packages
      include_tasks: Software/install_apt_packages.yml

    # - name: Install ROS Lyrical
    #   include_tasks: install_ros_lyrical.yml

    # - name: Set wallpaper
    #   become_user: josef
    #   dconf:
    #     key: "/org/gnome/desktop/background/picture-uri"
    #     value: "'file:///usr/share/backgrounds/ubuntu-default-greyscale-wallpaper.png'"

    # - name: copy dotfiles
    #   include_tasks: dotfiles/dotfiles.yml

    - name: Install Chrome
      include_tasks: Software/install_chrome.yml

    - name: Install Docker
      include_tasks: Software/install_docker.yml

    - name: Install VS Code
      include_tasks: Software/install_vscode.yml

    - name: Install hterm
      include_tasks: Software/install_hterm.yml

    - name: Install Joplin
      include_tasks: Software/install_joplin.yml

    - name: Install NoMachine
      include_tasks: Software/install_no_machine.yml

    - name: Enable Chinese Pinyin Keyboard
      include_tasks: chinse_pinyin_keyboard.yml
  
  handlers:
    - name: restart docker
      ansible.builtin.systemd:
        name: docker
        state: restarted
